version: 43.0.9
pageUuid: 8d027a6c-d11d-11ee-b736-179e67a322fe
appTemplate:
  appMaxWidth: 100%
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
      multiplayerEditingEnabled: false
      disableMultiplayerEditing: false
  version: 3.30.5
  experimentalDataTabEnabled: true
